import {
  MdDashboard,
  MdViewList,
  MdAccountTree,
  MdCategory,
  MdScience,
  MdRestaurant,
  MdStar,
  MdTune,
  MdHealthAndSafety,
  MdInventory2,
  MdPeople,
  MdSecurity,
  MdRateReview,
  MdSupportAgent,
  MdNotifications,
  MdAdd,
  MdFactCheck,
  MdFavorite,
  MdQrCodeScanner,
  MdStorefront,
} from "react-icons/md";
import type { IconType } from "react-icons";

export type CommandKind = "page" | "create" | "food";

export type AdminCommand = {
  id: string;
  label: string;
  hint: string;
  href: string;
  keywords: string;
  group: string;
  icon: IconType;
  kind: CommandKind;
  roles?: string[];
};

export const ADMIN_COMMANDS: AdminCommand[] = [
  {
    id: "dashboard",
    label: "Overview",
    hint: "Nutrition platform home — review, facts, scores",
    href: "/dashboard",
    keywords: "home overview kpis",
    group: "Navigate",
    icon: MdDashboard,
    kind: "page",
  },
  {
    id: "queue",
    label: "Review queue",
    hint: "Pending foods and unpublished drafts",
    href: "/queue",
    keywords: "queue pending drafts review approve",
    group: "Catalog",
    icon: MdFactCheck,
    kind: "page",
  },
  {
    id: "app-desk",
    label: "App desk",
    hint: "Assessment, scan, store, safety, coaching",
    href: "/app",
    keywords: "app scan store quiz premium nutritionist assessment",
    group: "Live app",
    icon: MdStorefront,
    kind: "page",
  },
  {
    id: "scans",
    label: "Scan desk",
    hint: "Barcodes, pack photos, duplicate GTINs",
    href: "/scans",
    keywords: "scan barcode gtin camera photo duplicate",
    group: "Live app",
    icon: MdQrCodeScanner,
    kind: "page",
  },
  {
    id: "products",
    label: "Catalog",
    hint: "Barcode, brand, facts, FOPL, scores",
    href: "/products",
    keywords: "products foods labels barcode",
    group: "Catalog",
    icon: MdViewList,
    kind: "page",
  },
  {
    id: "add-product",
    label: "Add food product",
    hint: "Create a new catalog item",
    href: "/add-product",
    keywords: "create new product food",
    group: "Create",
    icon: MdAdd,
    kind: "create",
  },
  {
    id: "ingredients",
    label: "Ingredients",
    hint: "Label dictionary for allergens and intolerance",
    href: "/ingredients",
    keywords: "ingredients sugar milk wheat additive",
    group: "Catalog",
    icon: MdRestaurant,
    kind: "page",
  },
  {
    id: "brands",
    label: "Brands & makers",
    hint: "Search brands and manufacturers",
    href: "/brands",
    keywords: "brand manufacturer maker recall",
    group: "Catalog",
    icon: MdInventory2,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "servings",
    label: "Serving sizes",
    hint: "g, ml, cups used on the facts panel",
    href: "/servings",
    keywords: "serving uom gram millilitre cup portion",
    group: "Nutrition science",
    icon: MdTune,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "level1",
    label: "Main category",
    hint: "Food tree level 1",
    href: "/level1",
    keywords: "taxonomy tree main category level1",
    group: "Food tree",
    icon: MdAccountTree,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "level2",
    label: "Category",
    hint: "Food tree level 2",
    href: "/level2",
    keywords: "taxonomy category level2",
    group: "Food tree",
    icon: MdCategory,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "level3",
    label: "Sub-category",
    hint: "Food tree level 3",
    href: "/level3",
    keywords: "taxonomy subcategory level3",
    group: "Food tree",
    icon: MdCategory,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "level4",
    label: "Nest category",
    hint: "Food tree level 4",
    href: "/level4",
    keywords: "taxonomy nest level4",
    group: "Food tree",
    icon: MdCategory,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "rda",
    label: "RDA / daily values",
    hint: "%DV used on nutrition facts",
    href: "/rda",
    keywords: "rda daily value dv micronutrient",
    group: "Nutrition science",
    icon: MdScience,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "nutrient",
    label: "Nutrient library",
    hint: "Energy, macros, micros, units",
    href: "/nutrient",
    keywords: "nutrition nutrients vitamins minerals",
    group: "Nutrition science",
    icon: MdRestaurant,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "scores",
    label: "HNSS scores",
    hint: "Scoring models for foods",
    href: "/scores",
    keywords: "hnss score fopl rating",
    group: "Nutrition science",
    icon: MdStar,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "add-score",
    label: "Add HNSS score",
    hint: "Define a new scoring model",
    href: "/add-score",
    keywords: "create score hnss",
    group: "Create",
    icon: MdAdd,
    kind: "create",
    roles: ["admin"],
  },
  {
    id: "dynamics",
    label: "FOPL, food type & UOM",
    hint: "Certificates, concerns, measurement units",
    href: "/dynamics",
    keywords: "dynamics fopl certificate uom unit food type concern",
    group: "Nutrition science",
    icon: MdTune,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "lifestyle",
    label: "Activity, goals & diet",
    hint: "Activity level, goal, food interest, diet, temporary concern",
    href: "/activity-level",
    keywords: "diet goal exercise lifestyle activity food interest temporary concern",
    group: "Nutrition science",
    icon: MdFavorite,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "allergies",
    label: "Allergies",
    hint: "Major and minor allergens",
    href: "/allergies",
    keywords: "allergy allergen safety",
    group: "Dietary safety",
    icon: MdHealthAndSafety,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "intolerance",
    label: "Food intolerance",
    hint: "Major and minor intolerances",
    href: "/food-intolerance",
    keywords: "intolerance lactose gluten",
    group: "Dietary safety",
    icon: MdInventory2,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "users",
    label: "Members",
    hint: "BMI, calories, diets, and allergies",
    href: "/users",
    keywords: "users members accounts bmi calories",
    group: "People",
    icon: MdPeople,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "roles",
    label: "Roles",
    hint: "Admin access and permissions",
    href: "/roles",
    keywords: "roles permissions staff",
    group: "People",
    icon: MdSecurity,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "reviews",
    label: "Product reviews",
    hint: "Community feedback on foods",
    href: "/reviews",
    keywords: "reviews ratings comments",
    group: "Operations",
    icon: MdRateReview,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "contacts",
    label: "Support",
    hint: "Contact messages from the app",
    href: "/contacts",
    keywords: "support contacts help",
    group: "Operations",
    icon: MdSupportAgent,
    kind: "page",
    roles: ["admin"],
  },
  {
    id: "notifications",
    label: "Notifications",
    hint: "Push and in-app messages",
    href: "/notifications",
    keywords: "notifications alerts push",
    group: "Operations",
    icon: MdNotifications,
    kind: "page",
    roles: ["admin"],
  },
];

export const QUICK_CREATE = ADMIN_COMMANDS.filter((item) => item.kind === "create");

export function filterCommands(query: string, role?: string) {
  const q = query.trim().toLowerCase();
  return ADMIN_COMMANDS.filter((item) => {
    if (item.roles && !item.roles.includes(role || "")) return false;
    if (!q) return true;
    return `${item.label} ${item.hint} ${item.keywords}`.toLowerCase().includes(q);
  });
}
